# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 10000

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[>](bold purple)"

[aws]
disabled = true
[gcloud]
disabled = true
[package]
disabled = true
[nodejs]
disabled = true
