#! /bin/sh
# Launch sxhkd for bspwm
sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# Launch Polybar
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X
BORDER_COLOR="#FF69B4"
if [ -f "$HOME/.cache/wal/colors.sh" ]; then
  . "${HOME}/.cache/wal/colors.sh"
  BORDER_COLOR=$color4
fi
bspc config border_width         2
bspc config focused_border_color "$BORDER_COLOR"
bspc config window_gap           5
bspc config top_padding          25
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config automatic_scheme longest_side
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Steam state=floating
bspc rule -a "jetbrains-studio" state=floating
bspc config ignore_ewmh_focus false
bspc config ignore_ewmh_fullscreen none
bspc config ignore_ewmh_struts false
bspc config honor_size_hints true

# bspc config external_rules_command ./external_rules

# ##### Fixing Resources per Resolution
LOCAL_RES=$(xrandr | grep "*" | cut -d"x" -f1)
if [ "$LOCAL_RES" -gt "2000" ]; then
  xrdb -merge ~/.4k.Xresources
fi
