#!/bin/sh
#      _  _      ____               _
#     | || |__  |  _ \  ___    ___ | |__    __ _
#  _  | || '_ \ | |_) |/ _ \  / __|| '_ \  / _` |
# | |_| || | | ||  _ <| (_) || (__ | | | || (_| |
#  \___/ |_| |_||_| \_\\___/  \___||_| |_| \__,_|

helpFunction()
{
    printf "Usage: $0 [salcp] -A ADDING_PARAMETERS -C COMMIT_MESSAGE\n"
    printf "\t -a git add --all\n"
    printf "\t -A git add OPTARG\n"
    printf "\t -f git pull\n"
    printf "\t -F git pull OPTARG\n"
    printf "\t -h helpFunction\n"
    printf "\t -p git push\n"
    printf "\t -P git push OPTARG\n"
    printf "\t -l git log\n"
    printf "\t -c git commit\n"
    printf "\t -C git commit -m OPTARG\n"
    printf "\t -s git status\n"
    exit 1 # Exit script after printing help
}

while getopts ":aAfFcCpP:slh" opt; do
  case "$opt" in
    a)
      git add --all
      ;;
    A)
      read -p "Add: " userInput
      git add $userInput
      ;;
    c)
      git commit -m "Updating"
      ;;
    C)
      printf "Please add you message\n"
      read -p "Commit: " userInput
      git commit -m "$userInput"
      ;;
    f)
      git pull
      ;;
    F)
      printf "Which branch?\n"
      read -p "Branch: " userInput
      git pull $userInput
      ;;
    h)
      helpFunction
      ;;
    p)
      git push
      ;;
    P)
      git push "$OPTARG"
      ;;
    l)
      git log
      ;;
    s)
      git status
      ;;
    *)
      helpFunction
      ;;
  esac
done
