#!/bin/bash
# i3-msg floating enable
if [[ $(i3-msg -t get_marks) == *"$1"* ]]; then
  echo "okay"
  i3-msg [con_mark="$1"] scratchpad show 
else 
  i3-msg mark $1, move scratchpad, scratchpad show
fi
