#!/bin/bash
#     _  ____               _
#    | ||  _ \  ___    ___ | |__    __ _
# _  | || |_) |/ _ \  / __|| '_ \  / _` |
#| |_| ||  _ <| (_) || (__ | | | || (_| |
# \___/ |_| \_\\___/  \___||_| |_| \__,_|

declare -A options=(
  ["push"]="rclone sync ~/drive/ onedrive: -vv"
  ["pull"]="rclone sync onedrive: ~/drive/ -vv"
)
choice=$(echo "${!options[@]}" | tr " " "\n" | rofi -dmenu -p "Sync Action")
if [ "$choice" ]; then
  # Execute choiced command
  notify-send "Syncing ~/oneDrive" "Starting Syncing"
  kitty -e bash -c "${options[$choice]} && read -p 'Press enter to continue'"
  notify-send "Sync ~/oneDrive" "Done!"
fi
