#!/usr/bin/env bash
input=$(cat)

if [ "$(uname)" == "Darwin" ]; then
  printf '%s' "$input" | pbcopy
elif [ "$WM" == "sway" ] || [ "$XDG_SESSION_TYPE" == "wayland" ]; then
  printf '%s' "$input" | wl-copy "$@"
else
  printf '%s' "$input" | xclip -in -selection clipboard
fi
