#!/bin/sh
#      _ _     ____            _
#     | | |__ |  _ \ ___   ___| |__   __ _
#  _  | | '_ \| |_) / _ \ / __| '_ \ / _` |
# | |_| | | | |  _ < (_) | (__| | | | (_| |
#  \___/|_| |_|_| \_\___/ \___|_| |_|\__,_|

CHANGED="$(stat -c %y ~/.cache/corona)"
DATA="$(echo $CHANGED | cut -d' ' -f1)"
HOUR="$(echo $CHANGED | cut -d' ' -f2 | cut -d':' -f1)"

[ "$DATA" = "$(date '+%Y-%m-%d')" ] && [ "$HOUR" = "$(date '+%H')" ] ||
  curl -s https://corona-stats.online/brazil > ~/.cache/corona
awk '/Brazil/ {print "😷"$7 " 🔺"$9" " "🚨"$12}' ~/.cache/corona | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"
