#!/usr/bin/env bash
# List options to pen a new session, window, pane or horizontal pane by location
launcher_cmd() {
  fzf-tmux -d 35% --multi --exit-0 --cycle --reverse --bind='ctrl-r:toggle-all' --bind='ctrl-s:toggle-sort' --no-preview --header="Launch project"
}

# Choose Project
launcher_cmd < "$HOME/.config/tmux-project.config" | { read -r path name
  if [[ "$name" ]]; then
    tmux select-window -t $name || tmux new-window -c $path -n $name 'nvim . -c :Files ; bash'
  elif [[ "$path" ]]; then
    tmux new-window -c $path 'nvim . -c :Files ; bash' 
  fi
}
