#!/usr/bin/env bash
# List options to pen a new session, window, pane or horizontal pane by location
launcher_cmd() {
  fzf-tmux -d 35% --multi --exit-0 --cycle --reverse --bind='ctrl-r:toggle-all' --bind='ctrl-s:toggle-sort' --no-preview --header="Launch project"
}

# Choose Project
launcher_cmd < "$HOME/.config/tmux-project.config" | { read -r path name
  tmux switch-client -t $name || tmux new-session -d -c $path -s $name -n $name 'nvim . -c :Files ; bash' && tmux switch-client -t $name
}
