#!/usr/bin/env bash
# List options to pen a new session, window, pane or horizontal pane by location
launcher_cmd() {
  fzf-tmux -d 35% --multi --exit-0 --cycle --reverse --bind='ctrl-r:toggle-all' --bind='ctrl-s:toggle-sort' --no-preview --header="Launch project"
}

# Choose Project
launcher_cmd < "$HOME/.config/tmux-projects.config" | { read -r path name
  if [[ -n $path ]]; then
    ((tmux switch-client -t code:$name) || (tmux new-window -c $path -t code: -n $name 'nvim . -c "lua my_find_files()" ; bash' && tmux switch-client -t code:$name))
  fi
}
